import { ApiProperty } from '@nestjs/swagger';
import { user_provider as Provider } from 'generated/prisma/enums';

export class User {
  @ApiProperty({
    description: 'User ID, generated by UUID',
    required: true,
    type: 'string',
    example: '2313w49-0db7-4v79-aacc-52624343bf2t',
  })
  id: string;

  @ApiProperty({
    description: 'Username',
    required: true,
    type: 'string',
    example: 'Steve',
  })
  username: string;

  @ApiProperty({
    description: 'Email',
    required: true,
    type: 'string',
    example: 'youremail@example.com',
  })
  email: string;

  @ApiProperty({
    description: 'Email Verified',
    required: true,
    type: 'boolean',
    example: false,
  })
  email_verified: boolean;

  @ApiProperty({
    description: 'Authentication provider',
    required: true,
    enum: Provider,
    example: Provider.Email,
  })
  provider: Provider;

  @ApiProperty({
    description: 'Date when the user was created',
    required: true,
    type: 'string',
    format: 'date-time',
    example: '2025-01-01T00:00:00.000Z',
  })
  created_at: Date;

  @ApiProperty({
    description: "Date of the user's last login",
    nullable: true,
    required: false,
    type: 'string',
    format: 'date-time',
    example: '2025-01-01T00:00:00.000Z',
  })
  last_login?: Date | null;
}
